name: fairfield_housing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - gdal
  - geopandas
  - shapely
  - fiona
  - pyproj
  - rtree
  - duckdb
  - networkx
  - osmnx
  - jupyterlab
  - ipywidgets
  - nodejs
  - pip
  - pip:
      - keplergl
      - pydeck
