name: bestschooldistricts-py310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - requests
  - beautifulsoup4
  - selenium
  - geopandas
  - gdal
  - fiona
  - shapely
  - pyproj
  - rtree
  - pip:
      - simplekml==1.3.6
      - fake-useragent==2.0.3
      - undetected-chromedriver==3.5.5
      - selenium-stealth==1.0.6
      - scrapy-rotating-proxies==0.6.2
      - 2captcha-python==1.5.1
